import { useEffect, useState } from 'react'
import type { AttackResponse, Evaluation } from './types'
import { money, percent } from './format'

const API = import.meta.env.VITE_API_URL ?? 'http://localhost:8000/api'
const title = (value:string) => value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())

function Stream() {
  const rows = [['Legitimate','Established device, normal purchase'],['Legitimate','Recent address change, purchase'],['Fraud','Recent address change, purchase'],['Legitimate','Established device, normal purchase']]
  return <div className="stream-card"><div className="stream-head"><span>Incoming transaction stream</span><span className="live">steady state</span></div>{rows.map((r,i)=><div className="stream-row" key={i}><span className={`signal ${r[0].toLowerCase()}`}></span><span><b>{r[0]}</b><small>{r[1]}</small></span><span className="muted">Allowed</span></div>)}<div className="stream-note">Synthetic labeled traffic · equal transaction values</div></div>
}

function Score({name,version,evaluation}:{name:string,version:'v1'|'v2',evaluation:Evaluation}) {
  const metrics=evaluation[version].metrics
  return <article className="score"><div><span className="version">{version.toUpperCase()}</span><h3>{name}</h3></div><div className="scores"><div><strong>{percent(metrics.fraud_recall)}</strong><small>Recall</small></div><div><strong>{percent(metrics.intervention_precision)}</strong><small>Precision</small></div></div></article>
}

export function App(){
  const [attack,setAttack]=useState<AttackResponse|null>(null),[evaluation,setEvaluation]=useState<Evaluation|null>(null)
  const [busy,setBusy]=useState(false),[error,setError]=useState('')
  useEffect(()=>{fetch(`${API}/evaluation`).then(r=>r.json()).then(setEvaluation).catch(()=>setError('The local API is not available.'))},[])
  async function run(){setBusy(true);setError('');try{const r=await fetch(`${API}/attacker/run`,{method:'POST'});if(!r.ok)throw Error();setAttack(await r.json())}catch{setError('Could not run the simulation.')}finally{setBusy(false)}}
  const divergence=attack?.comparison.first_decision_divergence
  return <main>
    <nav><span>Adversarial fraud testing</span><span>Goal 1 · deterministic demonstration</span></nav>
    <header><div className="intro"><p className="kicker">Prospective testing for fraud controls</p><h1>Find weaknesses before real attackers do.</h1><p className="lead">A bounded simulated attacker interacts with a stateful fraud system through the same restricted feedback an attacker would receive. Successful campaigns become deterministic regression tests for the defender.</p><button onClick={run} disabled={busy}>{busy?'Running simulation…':attack?'Run the same simulation again':'Run a simulated attack'}</button>{error&&<p className="error">{error}</p>}</div><Stream/></header>

    <section className="how"><p className="kicker">What this demonstration does</p><div className="steps"><article><span>1</span><h2>Observe a baseline</h2><p>A synthetic stream contains legitimate and fraudulent transactions. Defender v1 is the current policy under test.</p></article><article><span>2</span><h2>Inject a fake attack</h2><p>A transparent heuristic tries a bounded sequence of account actions using only released outcomes.</p></article><article><span>3</span><h2>Replay after a fix</h2><p>The exact sequence runs against v2, exposing fraud prevention and legitimate-user cost.</p></article></div></section>

    <section className="policy"><div><p className="kicker">The baseline policy</p><h2>What “Defender v1” means</h2><p>V1 is the existing fraud-control version. It trusts a previously established device enough to approve a purchase even when the shipping address has just changed. That combination is the planted weakness.</p></div><div className="rule"><small>DEFENDER V1 · PRIVATE RULE</small><code>trusted device → allow purchase</code><p>The recent address change does not reduce device trust.</p></div></section>

    {!attack?<section className="waiting"><p>Run the simulated attack to see the attacker and defender views side by side.</p></section>:<>
      <section className="result"><div className="result-head"><div><p className="kicker">Fake attack result</p><h2>One campaign, two different views</h2><p>The attacker sees acknowledgements and released outcomes. The defender retains state and the internal rule explanation.</p></div><div className="status">Campaign found <strong>v1 allows it</strong></div></div><div className="sides"><div className="side"><div className="side-title"><span>Attacker view</span><small>RESTRICTED</small></div>{attack.result.steps.map((s,i)=><div className="action" key={s.action.action_id}><span>{i+1}</span><div><b>{title(s.action.type)}</b><small>Observed outcome: {s.observation.outcome}</small></div></div>)}</div><div className="side defender"><div className="side-title"><span>Defender view</span><small>PRIVATE</small></div><div className="defender-context"><small>Complete state</small><p>Trusted device · recent address change · established payment instrument</p></div><div className="defender-context"><small>Matched v1 rule</small><p>Trusted device receives streamlined approval.</p></div><div className="decision">Decision <strong>ALLOW</strong></div></div></div></section>
      {divergence&&<section className="fix"><div><p className="kicker">The narrow fix</p><h2>V2 changes one condition, not the whole system.</h2><p>For 60 logical seconds after a shipping-address change, a high-value purchase no longer inherits the device’s full trust. It receives a challenge instead of automatic approval.</p></div><div className="change"><div><small>V1</small><strong>Allow</strong><span>Trusted device wins</span></div><span>→</span><div><small>V2</small><strong>Challenge</strong><span>Recent change reduces trust</span></div></div></section>}
      <section className="comparison"><p className="kicker">Exact open-loop replay · {attack.campaign_id}</p><h2>Step-by-step comparison</h2><div className="divergences"><span>First state divergence <b>{attack.comparison.first_state_divergence?.index ?? 'none'}</b></span><span>First decision divergence <b>{attack.comparison.first_decision_divergence?.index ?? 'none'}</b></span><span>First visible divergence <b>{attack.comparison.first_observation_divergence?.index ?? 'none'}</b></span><span>Final utility change <b>{money(attack.comparison.final_utility_divergence_minor)}</b></span></div><div className="table-wrap"><table><thead><tr><th>Step</th><th>Action</th><th>V1</th><th>V2</th><th>State</th><th>Decision</th><th>Visible</th><th>V1 utility</th><th>V2 utility</th></tr></thead><tbody>{attack.comparison.steps.map(s=><tr key={s.index}><td>{s.index+1}</td><td>{title(s.action.type)}</td><td>{s.v1_decision}</td><td>{s.v2_decision}</td><td>{s.state_diverged?'diff':'same'}</td><td>{s.decision_diverged?'diff':'same'}</td><td>{s.observation_diverged?'diff':'same'}</td><td>{money(s.v1_utility_minor)}</td><td>{money(s.v2_utility_minor)}</td></tr>)}</tbody></table></div></section>
    </>}

    {evaluation&&<section className="evaluation"><div><p className="kicker">Synthetic evaluation</p><h2>Did the fix improve the defender?</h2><p>Every transaction has equal value, so recall and intervention precision remain primary. Challenges count as interventions and caught fraud, not blocks.</p></div><div className="score-grid"><Score name="Baseline / current policy" version="v1" evaluation={evaluation}/><Score name="Narrow patched policy" version="v2" evaluation={evaluation}/></div><div className="table-wrap"><table><thead><tr><th>Supporting metric</th><th>V1</th><th>V2</th></tr></thead><tbody>{['benign_approval_rate','false_intervention_rate','benign_challenge_rate'].map(k=><tr key={k}><td>{title(k)}</td><td>{percent(evaluation.v1.metrics[k])}</td><td>{percent(evaluation.v2.metrics[k])}</td></tr>)}{['fraudulent_value_allowed_minor','legitimate_value_blocked_minor','attacker_utility_minor','defender_utility_minor'].map(k=><tr key={k}><td>{title(k)}</td><td>{money(evaluation.v1.metrics[k])}</td><td>{money(evaluation.v2.metrics[k])}</td></tr>)}<tr><td>Review volume</td><td>{evaluation.v1.metrics.review_volume}</td><td>{evaluation.v2.metrics.review_volume}</td></tr></tbody></table></div><p className="tradeoff">{evaluation.synthetic_warning} V2 catches the planted attack but challenges one legitimate recent-change case; it is a narrow patch, not a block-everything tier.</p><details><summary>Metric policy and utility coefficients</summary><p>{evaluation.challenge_treatment}</p><code>{JSON.stringify(evaluation.utility_coefficients)}</code></details></section>}
    <footer><strong>Scope:</strong> deterministic synthetic demonstration, not a fraud model or production benchmark.</footer>
  </main>
}
