import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { App } from './App'
const evaluation={synthetic_warning:'x',challenge_treatment:'A challenge counts as an intervention.',utility_coefficients:{challenge_cost:2000},v1:{metrics:{fraud_recall:0,intervention_precision:0,benign_approval_rate:1,false_intervention_rate:0,benign_challenge_rate:0,fraudulent_value_allowed_minor:300000,legitimate_value_blocked_minor:0,review_volume:0,attacker_utility_minor:280000,defender_utility_minor:-300000},rows:[{case_id:'ordinary',label:'benign',amount_minor:150000,decision:'allow'}]},v2:{metrics:{fraud_recall:.5,intervention_precision:.5,benign_approval_rate:.75,false_intervention_rate:.25,benign_challenge_rate:.25,fraudulent_value_allowed_minor:150000,legitimate_value_blocked_minor:0,review_volume:0,attacker_utility_minor:130000,defender_utility_minor:-154000},rows:[{case_id:'ordinary',label:'benign',amount_minor:150000,decision:'allow'}]}}
const action={action_id:'a',type:'attempt_purchase',timestamp:0,payload:{amount_minor:150000}},observation={action_id:'a',action_type:'attempt_purchase',timestamp:0,acknowledged:true,outcome:'allow',remaining_budget:4}
const attack={campaign_id:'campaign-x',campaign:[action],search_trace:[{candidate:1,submitted_actions:[action],action_costs:[3],observations:[observation],released_utility_minor:140000,search_status:'stopped: first profitable campaign'}],result:{steps:[{action,observation,utility:140000}],utility_minor:140000,replay_hash:'abc'}}
const step={index:0,action,v1_decision:'allow',v2_decision:'challenge',v1_observation:observation,v2_observation:{...observation,outcome:'challenge'},state_diverged:false,decision_diverged:true,observation_diverged:true,v1_utility_minor:140000,v2_utility_minor:-10000}
const run=(v:string)=>({identity:{fixture_id:'established_account',fixture_version:'1',engine_version:'1',defender_version:v,disclosure_policy_version:'transaction_context.v1',scoring_policy_version:'utility.v1',seed:0},steps:[{action,event:{rule_id:'rule',internal_reason:'reason',decision:v==='v1'?'allow':'challenge'},observation}],replay_hash:`hash-${v}`})
const analyst={campaign_id:'campaign-x',current_rule:run('v1'),proposed_rule:run('v2'),comparison:{v1:{utility_minor:140000},v2:{utility_minor:-10000},steps:[step],first_state_divergence:null,first_decision_divergence:step,first_observation_divergence:step,final_utility_divergence_minor:-150000}}
beforeEach(()=>{location.hash='#question';vi.stubGlobal('fetch',vi.fn((url:string)=>Promise.resolve({ok:true,json:()=>Promise.resolve(url.includes('/scenario')?{fixture_id:'established_account'}:url.includes('/evaluation')?evaluation:url.includes('/analyst/')?analyst:attack)})))})
afterEach(()=>cleanup())
describe('case study',()=>{
 it('navigates with tabs, hashes, previous, and next',async()=>{render(<App/>);fireEvent.click(screen.getByRole('button',{name:/the fake attacker/i}));expect(location.hash).toBe('#attacker');expect(screen.getByRole('heading',{name:'A short deterministic search'})).toBeVisible();fireEvent.click(screen.getByRole('button',{name:/previous/i}));expect(location.hash).toBe('#question');location.hash='#how-it-works';window.dispatchEvent(new HashChangeEvent('hashchange'));expect(await screen.findByRole('heading',{name:'Small pieces with explicit boundaries'})).toBeVisible()})
 it('renders the synthetic warning and metrics',async()=>{location.hash='#trade-off';render(<App/>);expect(await screen.findByText(/small synthetic fixture/i)).toBeVisible();expect(screen.getAllByText('50%').length).toBeGreaterThan(0);expect(screen.getAllByText('Benign Approval Rate').length).toBeGreaterThan(0)})
 it('renders candidates, rule names, labels, and an absent difference',async()=>{location.hash='#attacker';render(<App/>);fireEvent.click(await screen.findByRole('button',{name:'Run the fake attacker'}));expect(await screen.findByText('Candidate 1')).toBeVisible();location.hash='#replay';window.dispatchEvent(new HashChangeEvent('hashchange'));await waitFor(()=>expect(screen.getByText('First private-state difference')).toBeVisible());expect(screen.getByText('none')).toBeVisible();expect(screen.getAllByText(/Current rule/).length).toBeGreaterThan(0);expect(screen.getAllByText(/Proposed rule/).length).toBeGreaterThan(0);expect(screen.getAllByText('different').length).toBeGreaterThan(0)})
})
