import { useEffect, useState } from 'react'
import type { AnalystResponse, AttackResponse, Evaluation, Scenario } from './types'
import { money, percent, title } from './format'
const API=import.meta.env.VITE_API_URL??'http://localhost:8000/api'
export const tabs=['question','attacker','replay','trade-off','how-it-works'] as const
type Tab=typeof tabs[number]
const labels:Record<Tab,string>={question:'The question',attacker:'The fake attacker',replay:'The replay','trade-off':'The trade-off','how-it-works':'How it works'}
const hashTab=():Tab=>tabs.includes(location.hash.slice(1) as Tab)?location.hash.slice(1) as Tab:'question'
const Decision=({value}:{value:string|null})=><span className={`decision ${value??'none'}`}>{value??'none'}</span>

export function App(){
 const [active,setActive]=useState<Tab>(hashTab),[scenario,setScenario]=useState<Scenario|null>(null),[evaluation,setEvaluation]=useState<Evaluation|null>(null)
 const [attack,setAttack]=useState<AttackResponse|null>(null),[analyst,setAnalyst]=useState<AnalystResponse|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{const sync=()=>setActive(hashTab());addEventListener('hashchange',sync);if(!location.hash)history.replaceState(null,'','#question');return()=>removeEventListener('hashchange',sync)},[])
 useEffect(()=>{Promise.all([fetch(`${API}/scenario`).then(r=>r.json()),fetch(`${API}/evaluation`).then(r=>r.json())]).then(([s,e])=>{setScenario(s);setEvaluation(e)}).catch(()=>setError('The local API is not available.'))},[])
 const go=(tab:Tab)=>{setActive(tab);location.hash=tab}
 async function run(){setBusy(true);setError('');try{const r=await fetch(`${API}/attacker/run`,{method:'POST'});if(!r.ok)throw Error();const value=await r.json();setAttack(value);const a=await fetch(`${API}/analyst/campaigns/${value.campaign_id}`);if(!a.ok)throw Error();setAnalyst(await a.json())}catch{setError('Could not run the fake attacker.')}finally{setBusy(false)}}
 const index=tabs.indexOf(active)
 return <main><header className="masthead"><div><span className="eyebrow">A reproducible technical case study</span><strong>Stateful fraud rule thought experiment</strong></div><code>{scenario?.fixture_id??'loading'} / seed 0</code></header>
 <nav className="tabs" aria-label="Case study sections">{tabs.map((t,i)=><button key={t} className={t===active?'selected':''} aria-current={t===active?'page':undefined} onClick={()=>go(t)}><span>{i+1}</span>{labels[t]}</button>)}</nav>{error&&<p className="error">{error}</p>}
 {active==='question'&&<Question/>}{active==='attacker'&&<Attacker attack={attack} run={run} busy={busy}/>} {active==='replay'&&<Replay analyst={analyst}/>} {active==='trade-off'&&<Tradeoff evaluation={evaluation}/>} {active==='how-it-works'&&<How/>}
 <footer><button disabled={index===0} onClick={()=>go(tabs[index-1])}>← Previous</button><span>{index+1} of {tabs.length}</span><button disabled={index===tabs.length-1} onClick={()=>go(tabs[index+1])}>Next →</button></footer></main>
}

function Question(){return <section className="slide"><p className="kicker">The question</p><h1>Find weaknesses before real attackers do</h1><div className="reading"><p className="lead">This is a small, synthetic example of a problem in fraud controls. A rule can look reasonable when transactions are considered one at a time and still behave badly after a sequence of account changes.</p><p>The example uses an established account, a trusted device, an existing card, and an address change. A fake attacker gets a limited number of actions and only sees the responses released by the system.</p></div><div className="flow"><div>Fake attacker</div><span>→</span><div>public action interface</div><span>→</span><div>fraud rule<small>private account context enters here</small></div><i>private account context ↗</i></div><div className="two"><article><h2>Fixed fixture and budget</h2><table><tbody>{[['Account','Established'],['Device','Previously trusted'],['Address','Existing shipping address'],['Payment','Existing instrument'],['Budget','10 action-cost units'],['Seed','0'],['Time','Logical, starting at 0']].map(([a,b])=><tr key={a}><th>{a}</th><td>{b}</td></tr>)}</tbody></table></article><article><h2>Scope</h2><ul><li>The account and transaction data are synthetic.</li><li>The result does not estimate real fraud detection performance.</li><li>The fake attacker cannot see private defender state or rule definitions.</li><li>Time is logical rather than wall-clock time.</li><li>Repeated runs use the same fixture and inputs.</li></ul></article></div></section>}

function Attacker({attack,run,busy}:{attack:AttackResponse|null,run:()=>void,busy:boolean}){return <section className="slide"><p className="kicker">The fake attacker</p><h1>A short deterministic search</h1><p className="lead reading">This is not a trained model. It tries three hand-written candidates in order. Each starts from the same fixture, stays within a fixed budget, and stops at the first profitable sequence that matches the search condition.</p><div className="visibility"><article><h2>Attacker can see</h2><ul><li>Whether an action was accepted</li><li>Released transaction outcome</li><li>Generic validation errors</li><li>Remaining budget</li><li>Released utility</li></ul></article><article className="private"><h2>Attacker cannot see</h2><ul><li>Risk scores and matched rule identifiers</li><li>Internal reasons and hidden account history</li><li>Defender metadata and source configuration</li></ul></article></div><button className="primary" onClick={run} disabled={busy}>{busy?'Running…':'Run the fake attacker'}</button>{attack?<><p className="finding">The search found one profitable sequence within its small search space and budget. It did not find or prove a globally best attack.</p>{attack.search_trace.map(c=><article className="candidate" key={c.candidate}><div className="candidate-head"><h2>Candidate {c.candidate}</h2><span>{c.search_status}</span><strong>{money(c.released_utility_minor)}</strong></div><div className="table-wrap"><table><thead><tr><th>Submitted action</th><th>Logical time</th><th>Cost</th><th>Remaining budget</th><th>Released outcome</th><th>Released observation</th></tr></thead><tbody>{c.submitted_actions.map((a,i)=><tr key={a.action_id}><td>{title(a.type)}</td><td><code>{a.timestamp}</code></td><td>{c.action_costs[i]}</td><td>{c.observations[i].remaining_budget}</td><td>{c.observations[i].outcome}</td><td><code>{JSON.stringify(c.observations[i])}</code></td></tr>)}</tbody></table></div></article>)}</>:<p className="empty">Run the fake attacker to see every candidate it considers.</p>}</section>}

function Replay({analyst}:{analyst:AnalystResponse|null}){return <section className="slide"><p className="kicker">The replay</p><h1>The same actions, two rules</h1><div className="rules"><article><span>Current rule <code>v1</code></span><p>A trusted device is allowed to make the purchase even though the shipping address was just changed.</p></article><article><span>Proposed rule <code>v2</code></span><p>A high-value purchase made soon after a shipping-address change receives a challenge. Other trusted-device purchases keep their previous treatment.</p></article></div><p>The proposed rule is a narrow change, not a block-everything rule. Both runs use the exact stored, open-loop sequence. The fake attacker does not adapt after seeing the proposed rule.</p>{analyst?<><div className="differences">{[['First private-state difference',analyst.comparison.first_state_divergence],['First decision difference',analyst.comparison.first_decision_divergence],['First attacker-visible difference',analyst.comparison.first_observation_divergence]].map(([l,r])=><div key={l as string}><span>{l as string}</span><strong>{r?`step ${(r as typeof analyst.comparison.steps[number]).index+1}`:'none'}</strong></div>)}<div><span>Final utility difference</span><strong>{money(analyst.comparison.final_utility_divergence_minor)}</strong></div></div><div className="table-wrap"><table><thead><tr><th>Step / logical time / action</th><th>Current-rule decision</th><th>Proposed-rule decision</th><th>Attacker-visible response</th><th>Private state</th><th>Decision</th><th>Released response</th><th>Accumulated utility</th></tr></thead><tbody>{analyst.comparison.steps.map(s=><tr key={s.index}><td>{s.index+1} / <code>{s.action.timestamp}</code> / {title(s.action.type)}</td><td><Decision value={s.v1_decision}/></td><td><Decision value={s.v2_decision}/></td><td>current: {s.v1_observation.outcome}<br/>proposed: {s.v2_observation.outcome}</td><td>{s.state_diverged?'different':'same'}</td><td>{s.decision_diverged?'different':'same'}</td><td>{s.observation_diverged?'different':'same'}</td><td>{money(s.v1_utility_minor)} / {money(s.v2_utility_minor)}</td></tr>)}</tbody></table></div><Identity analyst={analyst}/><Private analyst={analyst}/></>:<p className="empty">Run the fake attacker in the previous section to create and replay the stored sequence.</p>}</section>}

function Identity({analyst}:{analyst:AnalystResponse}){const i=analyst.current_rule.identity;return <div className="technical"><h2>Replay identity</h2><dl>{[['Fixture',`${i.fixture_id} / ${i.fixture_version}`],['Engine',i.engine_version],['Rule versions',`${i.defender_version} / ${analyst.proposed_rule.identity.defender_version}`],['Disclosure policy',i.disclosure_policy_version],['Scoring policy',i.scoring_policy_version],['Seed',i.seed],['Current replay hash',analyst.current_rule.replay_hash],['Proposed replay hash',analyst.proposed_rule.replay_hash]].map(([k,v])=><div key={k}><dt>{k}</dt><dd><code>{v}</code></dd></div>)}</dl></div>}
function Private({analyst}:{analyst:AnalystResponse}){return <div className="technical"><h2>Private analyst view</h2><div className="table-wrap"><table><thead><tr><th>Step</th><th>Current matched rule</th><th>Current reason</th><th>Proposed matched rule</th><th>Proposed reason</th></tr></thead><tbody>{analyst.current_rule.steps.map((s,i)=><tr key={s.action.action_id}><td>{i+1}</td><td><code>{s.event.rule_id}</code></td><td>{s.event.internal_reason}</td><td><code>{analyst.proposed_rule.steps[i].event.rule_id}</code></td><td>{analyst.proposed_rule.steps[i].event.internal_reason}</td></tr>)}</tbody></table></div></div>}

function Tradeoff({evaluation}:{evaluation:Evaluation|null}){if(!evaluation)return <section className="slide"><p>Loading evaluation…</p></section>;return <section className="slide"><p className="kicker">The trade-off</p><h1>Did the proposed rule close the weakness without challenging everyone?</h1><p className="warning">These numbers describe a small synthetic fixture. They are useful for checking the behavior of this example, not for estimating production performance.</p><div className="primary-metrics">{(['v1','v2'] as const).map(v=><article key={v}><span>{v==='v1'?'Current rule':'Proposed rule'} <code>{v}</code></span><div><strong>{percent(evaluation[v].metrics.fraud_recall)}</strong><small>Recall</small><strong>{percent(evaluation[v].metrics.intervention_precision)}</strong><small>Intervention precision</small></div></article>)}</div><MetricTable evaluation={evaluation}/><h2>Synthetic corpus rows</h2><div className="table-wrap"><table><thead><tr><th>Case</th><th>Label</th><th>Amount</th><th>Current rule</th><th>Proposed rule</th></tr></thead><tbody>{evaluation.v1.rows.map((r,i)=><tr key={r.case_id}><td><code>{r.case_id}</code></td><td>{r.label}</td><td>{money(r.amount_minor)}</td><td><Decision value={r.decision}/></td><td><Decision value={evaluation.v2.rows[i].decision}/></td></tr>)}</tbody></table></div><div className="policy-note"><h2>How challenges count</h2><p>{evaluation.challenge_treatment}</p><h2>Utility coefficients</h2><dl>{Object.entries(evaluation.utility_coefficients).map(([k,v])=><div key={k}><dt><code>{k}</code></dt><dd>{k.includes('weight')?v:money(v)}</dd></div>)}</dl></div></section>}
function MetricTable({evaluation}:{evaluation:Evaluation}){return <div className="table-wrap"><table><thead><tr><th>Metric</th><th>Current rule</th><th>Proposed rule</th></tr></thead><tbody>{['benign_approval_rate','false_intervention_rate','benign_challenge_rate'].map(k=><tr key={k}><td>{title(k)}</td><td>{percent(evaluation.v1.metrics[k])}</td><td>{percent(evaluation.v2.metrics[k])}</td></tr>)}{['fraudulent_value_allowed_minor','legitimate_value_blocked_minor','attacker_utility_minor','defender_utility_minor'].map(k=><tr key={k}><td>{title(k)}</td><td>{money(evaluation.v1.metrics[k])}</td><td>{money(evaluation.v2.metrics[k])}</td></tr>)}<tr><td>Review volume</td><td>{evaluation.v1.metrics.review_volume}</td><td>{evaluation.v2.metrics.review_volume}</td></tr></tbody></table></div>}

function How(){return <section className="slide"><p className="kicker">How it works</p><h1>Small pieces with explicit boundaries</h1><div className="architecture"><div>React case study</div><span>│</span><div>FastAPI routes</div><span>│</span><div>application service</div><span>│</span><div>SQLite &nbsp; + &nbsp; pure engine</div><span>│</span><div>defender rule</div><span>│</span><div>public projection</div></div><div className="two"><article><h2>Engineering choices</h2><ul><li>A pure deterministic engine does not import FastAPI, SQLAlchemy, or React.</li><li>Typed actions use explicit validation, integer minor-unit money, logical time, and deterministic costs.</li><li>Idempotency keys make duplicate handling stable. Invalid actions are recorded.</li><li>Canonical JSON produces replay hashes.</li><li>SQLAlchemy stores fixtures, campaigns, actions, events, observations, replays, and comparisons in SQLite.</li><li>Defender logic and attacker projection stay separate.</li><li>State is reconstructed from the initial fixture and ordered records after restart.</li></ul></article><article><h2>Limitations</h2><ul><li>One fixed scenario</li><li>One small hand-written search</li><li>One synthetic corpus</li><li>No real transaction data or statistical claims</li><li>No machine-learning model</li><li>No authentication or production deployment design</li><li>No delayed feedback or campaign-family analysis</li></ul></article></div></section>}
